import os
from typing import Any

import metpy.calc as mpcalc
import metpy.constants as mpconst
import numpy as np
import xarray as xr
from metpy.units import units


def load_hrrr_data(file_path: str) -> xr.Dataset:
    """
    Load the NetCDF dataset generated by the HRRR download module.

    Parameters:
        file_path: Path to the NetCDF file.

    Returns:
        An xarray Dataset containing the weather data.
    """
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"Data file not found at {file_path}")
    print(f"Loading data from {file_path}...")
    return xr.open_dataset(file_path)


def process_profile_data(
    ds: xr.Dataset, settings: Any | None = None
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, dict]:
    """
    Extract profile and surface variables, attach units, and sort profile by pressure.

    Parameters:
        ds: The input xarray Dataset.
        settings: Optional settings object (e.g. SkewTPlotSettings)
            to inspect height_type.

    Returns:
        A tuple of:
        - p: pressure profile array (with hPa units)
        - T: temperature profile array (with degK units)
        - Td: dewpoint profile array (with degK units)
        - u: wind u-component profile array (with m/s units)
        - v: wind v-component profile array (with m/s units)
        - metadata: dict of general metadata and surface conditions
    """
    print("Processing profile and surface data...")

    # Identify the vertical dimension
    if "isobaricInhPa" in ds.coords:
        p = ds["isobaricInhPa"].values * units.hPa
    else:
        # Fallback: search for isobaric coordinate
        p_coords = [c for c in ds.coords if "isobaric" in c]
        if not p_coords:
            raise KeyError("No isobaric pressure coordinate found in dataset.")
        print(f"WARNING FALLBACK: Using coordinate '{p_coords[0]}' for pressure levels.")
        p = ds[p_coords[0]].values * units.hPa

    # Extract profile variables and attach units
    # Ensure 1D arrays by squeezing (handles the 'point' dimension if it exists)
    T = np.atleast_1d(ds["t"].values.squeeze()) * units.degK
    Td = np.atleast_1d(ds["dpt"].values.squeeze()) * units.degK
    u = np.atleast_1d(ds["u"].values.squeeze()) * units.meters / units.second
    v = np.atleast_1d(ds["v"].values.squeeze()) * units.meters / units.second
    z_geopotential_height = np.atleast_1d(ds["gh"].values.squeeze()) * units.meters

    # Extract surface variables
    t2m = ds["t2m"].values.item() * units.degK
    d2m = ds["d2m"].values.item() * units.degK
    sp = ds["sp"].values.item() * units.Pa
    sp = sp.to(units.hPa)
    orog = ds["orog"].values.item() * units.meters

    print(
        f"\nSurface pressure: {sp:.2f}, "
        f"2m temperature: {t2m:.2f}, "
        f"2m dewpoint: {d2m:.2f}, "
        f"Orography: {orog:.2f}\n"
    )

    # Convert geopotential height to MSL altitude if requested
    height_type = (
        getattr(settings, "height_type", "geopotential") if settings else "geopotential"
    )
    if height_type == "msl":
        print("Converting Geopotential Height to MSL Altitude...")
        geopotential = z_geopotential_height * mpconst.g
        z = mpcalc.geopotential_to_height(geopotential)
    else:
        z = z_geopotential_height

    # Sort profile by pressure (surface to top, i.e., decreasing pressure)
    idx = np.argsort(p)[::-1]
    p = p[idx]
    T = T[idx]
    Td = Td[idx]
    u = u[idx]
    v = v[idx]
    z = z[idx]

    # Gather metadata for plotting
    metadata = {
        "lat": ds.latitude.values.item(),
        "lon": ds.longitude.values.item(),
        "valid_time": ds.valid_time.values,
        "surface": {"t2m": t2m, "d2m": d2m, "sp": sp, "orog": orog},
        "profile_z": z,
    }

    # If valid_time is an array, take the first element
    if isinstance(metadata["valid_time"], np.ndarray):
        metadata["valid_time"] = metadata["valid_time"][0]

    return p, T, Td, u, v, metadata
